### ISSUE TITLE
The walkthrough doesn't mention tool head molds and the table required for them

### ISSUE THREAD

**Issue by SimonMeskens** [Katalliaan/Rubedo#75]
The blacksmith part needs to be reworded

**Comment by Katalliaan** [comment]
I'm looking at the blacksmith part right now. There's mention of both tool head molds and the carving table, although it is very much a wall of text right now. Additionally, because it's in markdown rather than mediawiki, you don't get a table of contents like we have on the [materials page](https://github.com/Katalliaan/Rubedo/wiki/Materials), which will make it harder to navigate as it gets built out.
